#' Generate coloured compositional biplot.
#'
#' Generates a coloured PCA biplot from a \code{prcomp} object
#'  generated by \code{omicplotr.clr} using \code{coloredBiplot}
#'  from the \code{compositions} package.
#'
#' @param x prcomp object generated by \code{omicplotr.clr}.
#' @param colourvector list of colours generated by \code{omciplotr.colvec}.
#' @param scale 0 = relationship between samples, 1 = relationship between rows
#'  default 0.
#' @param arrows show PCA arrows, default TRUE.
#' @param taxonomy taxonomy column from \code{omicplotr.filter} to plot points
#'  as taxonomic identifiers.
#' @param show.taxonomy show taxonomy as points, default 0. Required input is
#'  x$taxonomy.
#' @param tax.level numeric taxonomic level (kingdom =1, phylum =2...) to show
#'  if \code{show.taxonomy = TRUE}, default 6 (genus).
#' @param removenames replace sample names with points, default FALSE.
#' @param names.cex the size of sample names.
#' @param points.cex the size of points representing features (text size for
#'  taxonomic levels if \code{show.taxonomy = TRUE}).
#'
#' @export
#'


omicplotr.colouredPCA <- function(x, colourvector, scale = 0, arrows = TRUE,
     taxonomy = NULL, show.taxonomy = FALSE, tax.level = 6,
     removenames = FALSE, names.cex = 1.0, points.cex = 0.8, main = "Principal
     Component Analysis Biplot") {

    x.var <- sum(x$sdev ^ 2)
    PC1 <- paste("PC 1 Variance: %", round(sum(x$sdev[1] ^ 2) / x.var * 100, 1))
    PC2 <- paste("PC 2 Variance: %", round(sum(x$sdev[2] ^ 2) / x.var*100, 1))

    points <- c(rep(".", length(dimnames(x$rotation)[[1]])))
    if ((isTRUE(show.taxonomy)) & (!is.null(taxonomy))) {
        genus <- sapply(strsplit(as.character(taxonomy), ";"), "[", tax.level)
    }

    col = c("black", rgb(0, 0, 0, 0.4))

    #remove sample names
    if (isTRUE(removenames)) {
      xlabs <- c(rep(".", length(dimnames(x$x)[[1]])))
      names.cex = 5*names.cex
      points.cex = points.cex
    } else {
      xlabs = unlist(dimnames(x$x)[1])
      names.cex = names.cex
      points.cex = points.cex
      }

    #if taxonomy is present, plot using taxonomies
    if (!isTRUE(show.taxonomy)) {
      points <- points
    } else {
      if (isTRUE(show.taxonomy)) {
        points <- genus
      } else {
        points <- points
      }
    }

    coloredBiplot(
      x,
      col = col,
      main = main,
      cex.main = 1.5,
      cex = c(names.cex, points.cex),
      xlabs.col = colourvector,
      var.axes = arrows,
      scale = scale,
      xlab = PC1,
      ylab = PC2,
      xlabs = xlabs,
      ylabs = points
    )
}
