#' Plot coloured biplot.
#'
#' Create a coloured PCA biplot from a \code{prcomp} object
#'  generated by \code{omicplotr.clr}.
#'
#' @details Coloured PCA biplot is plotted using \code{coloredBiplot} from
#'  \code{zCompositions}. \code{omicplotr.colvec} generates a list of colours
#'  to be used when plotting the sample names.
#'
#' @param data "prcomp" object generated by \code{omicplotr.clr}.
#' @param colourvector List of colours generated by \code{omciplotr.colvec}.
#' @param scale 0 = relationship between samples, 1 = relationship between rows
#'  default 0.
#' @param arrows Show PCA arrows, default TRUE.
#' @param taxonomy Taxonomy column from \code{omicplotr.filter} to plot points
#'  as taxonomic identifiers.
#' @param show.taxonomy Show taxonomy as points, default 0. Required input is
#'  x$taxonomy.
#' @param tax.level Numeric taxonomic level (kingdom =1, phylum =2...) to show
#'  if \code{show.taxonomy = TRUE}, default 6 (genus).
#' @param removenames Replace sample names with points, default FALSE.
#' @param names.cex The size of sample names.
#' @param points.cex The size of points representing features (text size for
#'  taxonomic levels if \code{show.taxonomy = TRUE}).
#' @param main main Title for plot.
#'
#' @seealso \code{\link{omicplotr.colvec}}
#'
#' @export
#'

omicplotr.colouredPCA <- function(data, colourvector, scale = 0, arrows = TRUE,
     taxonomy = NULL, show.taxonomy = FALSE, tax.level = 6,
     removenames = FALSE, names.cex = 1.0, points.cex = 0.8, main = "Principal
     Component Analysis Biplot") {

    x.var <- sum(data$sdev ^ 2)
    PC1 <- paste("PC 1 Variance: %", round(sum(data$sdev[1] ^ 2) / x.var * 100, 1))
    PC2 <- paste("PC 2 Variance: %", round(sum(data$sdev[2] ^ 2) / x.var*100, 1))

    points <- c(rep(".", length(dimnames(data$rotation)[[1]])))
    if ((isTRUE(show.taxonomy)) & (!is.null(taxonomy))) {
        genus <- sapply(strsplit(as.character(taxonomy), "[[:punct:]]"), "[", tax.level)
    }

    col = c("black", rgb(0, 0, 0, 0.4))

    #remove sample names
    if (isTRUE(removenames)) {
      xlabs <- c(rep(".", length(dimnames(data$x)[[1]])))
      names.cex = 5*names.cex
      points.cex = points.cex
    } else {
      xlabs = unlist(dimnames(data$x)[1])
      names.cex = names.cex
      points.cex = points.cex
      }

    #if taxonomy is present, plot using taxonomies
    if (!isTRUE(show.taxonomy)) {
      points <- points
    } else {
      if (isTRUE(show.taxonomy)) {
        points <- genus
      } else {
        points <- points
      }
    }

    coloredBiplot(
      data,
      col = col,
      main = main,
      cex.main = 1.5,
      cex = c(names.cex, points.cex),
      xlabs.col = colourvector,
      var.axes = arrows,
      scale = scale,
      xlab = PC1,
      ylab = PC2,
      xlabs = xlabs,
      ylabs = points
    )
}
